[project]
name = "quantum-circuit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "qiskit[visualization]>=2.1.1",
    "qiskit-ibm-runtime>=0.41.0",
    "jupyter>=1.1.1",
    "qiskit-aer>=0.17.1",
]
